name: Urdu voice AI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools
          pip install buildozer kivy cython requests gradio

      - name: Initialize Buildozer
        run: |
          yes | buildozer init
          sed -i 's/title = My Application/title = Urdu AI Orator/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = urduaiorator/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = com.malik/' buildozer.spec
          echo "requirements = python3,kivy,gradio,requests" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Urdu_AI_Orator_APK
          path: /home/runner/work/**/bin/*.apk
