name: Android APK Builder (Stable 2025)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Create default buildozer.spec if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            cat > buildozer.spec <<'SPEC'
[app]
title = Urdu AI Orator
package.name = urduaiorator
package.domain = com.malik
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy,requests
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
[buildozer]
log_level = 2
warn_on_root = 0
SPEC
          fi

      - name: Pull Kivy Buildozer Docker image
        run: docker pull kivy/buildozer:latest

      - name: Build APK inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/kivy/hostcwd \
            -w /home/kivy/hostcwd \
            kivy/buildozer:latest \
            /bin/bash -c "buildozer android debug"
        timeout-minutes: 45

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: Urdu_AI_Orator_APK
          path: |
            bin/*.apk
            bin/*/*.apk
