name: Build Urdu AI Orator APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip
          pip install buildozer Cython==0.29.36 kivy==2.3.0

      - name: Create buildozer.spec dynamically
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Urdu AI Orator" >> buildozer.spec
          echo "package.name = urduaiorator" >> buildozer.spec
          echo "package.domain = org.malik" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy,requests" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.sdk_path = /opt/android-sdk" >> buildozer.spec
          echo "android.ndk_path = /opt/android-ndk" >> buildozer.spec

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Urdu_AI_Orator_APK
          path: bin/*.apk
